redis-ha:
  enabled: true

controller:
  replicas: 1

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

global:
  domain: argocd.jrconline.xyz

configs:
  params:
    server.insecure: true

server:
  service:
    type: NodePort
    # -- Server service annotations
  autoscaling:
    enabled: true
    minReplicas: 2
  ingress:
    enabled: true
    ingressClassName: alb
    annotations:
      external-dns.alpha.kubernetes.io/alias: true
      external-dns.alpha.kubernetes.io/hostname: argocd.jrconline.xyz
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

      alb.ingress.kubernetes.io/load-balancer-name: terraform-eks-argocd
      alb.ingress.kubernetes.io/group.name: terraform-eks-argocd
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"