# Ref - https://github.com/zitadel/zitadel/issues/3598#issuecomment-1289463922
# Ref - https://github.com/zitadel/zitadel-charts/blob/main/examples/1-postgres-insecure/zitadel-values.yaml

ingress:
  enabled: true
  className: alb
  annotations:
      external-dns.alpha.kubernetes.io/alias: true
      external-dns.alpha.kubernetes.io/hostname: zitadel.jrconline.xyz
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

      alb.ingress.kubernetes.io/load-balancer-name: terraform-eks-argocd
      alb.ingress.kubernetes.io/group.name: terraform-eks-argocd
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
      service.beta.kubernetes.io/aws-load-balancer-type: external
      service.beta.kubernetes.io/aws-load-balancer-internal: "false"
  hosts:
    - host: zitadel.jrconline.xyz
      paths:
        - path: /
          pathType: Prefix
  # tls: []

service:
  type: NodePort

zitadel:
  masterkey: x123456789012345678901234567891y
  configmapConfig:
    TLS:
      Enabled: false

# Additional environment variables
env:
  - name: ZITADEL_EXTERNALSECURE
    value: "false"
  - name: ZITADEL_DATABASE_POSTGRES_HOST
    value: management-postgresql.postgresql.svc.cluster.local
  - name: ZITADEL_DATABASE_POSTGRES_PORT
    value: "5432"
  - name: ZITADEL_DATABASE_POSTGRES_DATABASE
    value: "zitadel"
  - name: ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE
    value: "disable"
  - name: ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE
    value: "disable"
  - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
    value: zitadeluser
  - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
    value: zitadeluser
  # - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
  #   value: zitadel_queries
  # - name: ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
  #   value: password@123
  - name: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
    value: zitadeladmin
  - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
    value: zitadeladmin

  # configmapConfig:
  #   # ExternalSecure: false
  #   # ExternalDomain: 127.0.0.1.sslip.io
  #   TLS:
  #     Enabled: false
  #   Database:
  #     Postgres:
  #       Host: management-postgresql.postgresql.svc.cluster.local
  #       Port: 5432
  #       Database: zitadel
  #       MaxOpenConns: 20
  #       MaxIdleConns: 10
  #       MaxConnLifetime: 30m
  #       MaxConnIdleTime: 5m
  #       User:
  #         Username: postgres
  #         SSL:
  #           Mode: disable
  #       Admin:
  #         Username: postgres
  #         SSL:
  #           Mode: disable