

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: management
  namespace: argocd
  # annotations:
  #     argocd.argoproj.io/sync-wave: "-1"
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - https://charts.jetstack.io # cert-manager
    - https://kubernetes-sigs.github.io/external-dns/ # external-dns
    - https://prometheus-community.github.io/helm-charts # Prometheus
    - https://github.com/defyjoy/Terraform.git # app manifest repo
    - https://charts.external-secrets.io # external-secrets
  destinations:
    - namespace: "*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
