logLevel: debug
provider: 
  name: aws

# serviceAccount:
#   annotations: 
#     eks.amazonaws.com/role-arn: arn:aws:iam::727646503346:role/external-dns

region: "eu-west-1"

aws:
  zoneType: public

zoneIdFilters:
  - Z099080110OR3KUMVXE1F

ingressClassFilters: 
  - alb
domainFilters:
  - jrconline.xyz
policy: upsert-only
txtOwnerId: external-dns-public-Z099080110OR3KUMVXE1F
