apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/defyjoy/Terraform-EKS-ArgoCD.git
      ref: argo
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 7.8.13
      helm:
        valueFiles:
        - $argo/ArgoCD/manifests/helmcharts/argocd/argocd.values.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    syncOptions:
    - Validate=false
    automated:
      prune: true
      selfHeal: true
